{
 "title": "Kubernetes Pods (Prometheus)",
 "description": "A dashboard to view pod metrics by namespace and pod names.\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster. It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace" },
   { "name": "pod" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m]) * 100) by (pod)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "HAProxy Backend Response Latency (ms)",
   "type": "graph",
   "description": "HAProxy backend average response latency",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_average_response_latency_milliseconds"
    }
   ]
  },
  {
   "title": "HAProxy Connection Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_connections_total[1m]))"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod)"
    }
   ]
  }
 ]
}