---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haists-website
  namespace: haists-website
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: haists-website-anyuid
allowPrivilegedContainer: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - projected
  - secret
  - persistentVolumeClaim
users:
  - system:serviceaccount:haists-website:haists-website
priority: 10
