apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: homepage
data:
  settings.yaml: |
    title: Sentinel Dashboard
    favicon: https://cdn-icons-png.flaticon.com/512/1828/1828884.png
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Infrastructure:
        style: row
        columns: 5
      Platform:
        style: row
        columns: 3
      DevOps:
        style: row
        columns: 3
      Security:
        style: row
        columns: 1
      Media:
        style: row
        columns: 3
      Management:
        style: row
        columns: 1
