apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.${INTERNAL_DOMAIN}"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "external-secrets"
          secretRef:
            name: "vault-auth-token"
            namespace: "external-secrets"
            key: "token"
