apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kiali-metrics
  namespace: istio-system
  labels:
    app: kiali
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali
  endpoints:
    - port: tcp-metrics
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
