apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-metrics
  namespace: kyverno
  labels:
    app.kubernetes.io/part-of: kyverno
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kyverno
  endpoints:
    - port: metrics-port
      interval: 30s
