apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-root-pv
spec:
  capacity:
    storage: 20Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-nfs
  nfs:
    path: /mnt/DATA/data
    server: ${VAULT_SECONDARY_IP}
