apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - keycloak-admin-external-secret.yaml
  - postgresql-external-secret.yaml
  - postgresql-pvc.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - theme-configmap.yaml
  - keycloak-deployment.yaml
  - keycloak-service.yaml
  - keycloak-route.yaml
  - network-policies.yaml
