apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: keycloak
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        app.kubernetes.io/name: postgresql
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      serviceAccountName: postgresql-sa
      containers:
        - name: postgresql
          image: harbor.${INTERNAL_DOMAIN}/sentinel/postgres:16.8
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - shared_buffers=256MB
            - -c
            - effective_cache_size=1GB
            - -c
            - maintenance_work_mem=128MB
            - -c
            - work_mem=16MB
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 4Gi
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U keycloak -d keycloak
            failureThreshold: 360
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U keycloak -d keycloak
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U keycloak -d keycloak
            periodSeconds: 10
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
