apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ops-wazuh-creds
  namespace: sentinel-ops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ops-wazuh-creds
    creationPolicy: Owner
  data:
    - secretKey: WAZUH_USER
      remoteRef:
        key: wazuh/api
        property: username
    - secretKey: WAZUH_PASS
      remoteRef:
        key: wazuh/api
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ops-minio-creds
  namespace: sentinel-ops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ops-minio-creds
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: minio
        property: access_key
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: minio
        property: secret_key
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: minio
        property: endpoint
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ops-gitlab-token
  namespace: sentinel-ops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ops-gitlab-token
    creationPolicy: Owner
  data:
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: gitlab
        property: pat
    - secretKey: GITLAB_URL
      remoteRef:
        key: gitlab
        property: url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ops-proxmox-creds
  namespace: sentinel-ops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ops-proxmox-creds
    creationPolicy: Owner
  data:
    - secretKey: PROXMOX_TOKEN_ID
      remoteRef:
        key: proxmox
        property: api_token_id
    - secretKey: PROXMOX_TOKEN_SECRET
      remoteRef:
        key: proxmox
        property: api_token_secret
    - secretKey: PROXMOX_ENDPOINT
      remoteRef:
        key: proxmox
        property: endpoint
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ops-grafana-creds
  namespace: sentinel-ops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ops-grafana-creds
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_API_KEY
      remoteRef:
        key: grafana
        property: api_key
