---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vault-server
  description: HashiCorp Vault secrets management and JIT SSH certificate authority
  annotations:
    backstage.io/techdocs-ref: "url:http://${GITLAB_IP}/${GITLAB_NAMESPACE}/sentinel-iac/-/tree/main/techdocs/vault"
    grafana/dashboard-url: https://grafana.${INTERNAL_DOMAIN}
  links:
    - url: https://vault.${INTERNAL_DOMAIN}
      title: Vault UI
      icon: dashboard
  tags:
    - secrets
    - security
    - vm-service
    - overwatch
spec:
  type: vm
  lifecycle: production
  owner: platform-team
  system: sentinel-platform
  dependsOn:
    - resource:proxmox-proxmox-node-2
  providesApis:
    - vault-secrets-api
