---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: haists-website-dev-credentials
  namespace: haists-website-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: haists-website-dev-credentials
    creationPolicy: Owner
  data:
    - secretKey: HW_OIDC_CLIENT_SECRET
      remoteRef:
        key: keycloak/haists-website
        property: client_secret
    - secretKey: HW_CONTACT_RECIPIENT_EMAIL
      remoteRef:
        key: haists-website
        property: contact_recipient_email
