apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt-tunnel
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: http://${GITLAB_IP}/${GITLAB_NAMESPACE}/overwatch-gitops.git
    targetRevision: main
    path: clusters/overwatch/system/ingress/newt-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: pangolin-internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
