---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defectdojo-postgresql-data
  namespace: defectdojo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
