---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: defectdojo
  namespace: defectdojo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: defectdojo-postgresql
  namespace: defectdojo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: defectdojo-anyuid
  namespace: defectdojo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: defectdojo
    namespace: defectdojo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: defectdojo-postgresql-anyuid
  namespace: defectdojo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: defectdojo-postgresql
    namespace: defectdojo
