---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: harbor.${INTERNAL_DOMAIN}/sentinel/jaeger-all-in-one:1.62.0
    options:
      log-level: info
      memory:
        max-traces: "100000"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
  storage:
    type: memory
    options:
      memory:
        max-traces: "100000"
  ingress:
    enabled: false
