apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-208
  namespace: monitoring
spec:
  host: grafana.${INTERNAL_DOMAIN}
  to:
    kind: Service
    name: grafana
  port:
    targetPort: service
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
