apiVersion: v1
kind: ServiceAccount
metadata:
  name: netbox
  namespace: netbox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netbox-postgresql
  namespace: netbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netbox-anyuid
  namespace: netbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: netbox
    namespace: netbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netbox-postgresql-anyuid
  namespace: netbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: netbox-postgresql
    namespace: netbox
