---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: netbox
  namespace: netbox
spec:
  hosts:
    - netbox.${INTERNAL_DOMAIN}
  gateways:
    - istio-ingress/sentinel-gateway
  http:
    - route:
        - destination:
            host: netbox.netbox.svc.cluster.local
            port:
              number: 80
