apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
  annotations:
    policies.kyverno.io/title: Require Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      All pods must have the app.kubernetes.io/name label for inventory
      and asset management. Maps to NIST 800-53 control CM-8.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-app-label
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - backstage
                - defectdojo
                - demo
                - harbor
                - haists-website
                - homepage
                - keycloak
                - matrix
                - media
                - monitoring
                - netbox
                - nfs-provisioner
                - overwatch-console
                - pangolin-internal
                - sentinel-ops
      validate:
        message: "The label 'app.kubernetes.io/name' is required."
        pattern:
          metadata:
            labels:
              app.kubernetes.io/name: "?*"
