---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-credentials
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: harbor-credentials
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor
        property: admin_password
    - secretKey: secretKey
      remoteRef:
        key: harbor
        property: secret_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-database
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: harbor-database
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: harbor
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-oidc
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: harbor-oidc
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: keycloak/harbor
        property: client_secret
