apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: http://${GITLAB_IP}/${GITLAB_NAMESPACE}/overwatch-gitops.git
    targetRevision: main
    path: apps/ntfy
  destination:
    server: https://kubernetes.default.svc
    namespace: health-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
