apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-storage
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: http://${GITLAB_IP}/${GITLAB_NAMESPACE}/overwatch-gitops.git
    targetRevision: main
    path: clusters/overwatch/system/static-storage
  destination:
    server: https://kubernetes.default.svc
    # No namespace implies cluster level, or default
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
