apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-web
  namespace: matrix
  labels:
    app: element-web
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: element-web
  template:
    metadata:
      labels:
        app: element-web
        app.kubernetes.io/name: element-web
    spec:
      serviceAccountName: matrix-sa
      enableServiceLinks: false
      containers:
        - name: element-web
          image: harbor.${INTERNAL_DOMAIN}/sentinel/element-web:v1.12.11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: element-config
              mountPath: /app/config.json
              subPath: config.json
            - name: element-config
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: nginx.conf
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: element-config
          configMap:
            name: element-config
