apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-postgresql-credentials
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: matrix-postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: matrix/postgresql
        property: db_name
    - secretKey: POSTGRES_USER
      remoteRef:
        key: matrix/postgresql
        property: db_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: matrix/postgresql
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-synapse-secrets
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: matrix-synapse-secrets
    creationPolicy: Owner
  data:
    - secretKey: registration_shared_secret
      remoteRef:
        key: matrix/synapse
        property: registration_shared_secret
    - secretKey: macaroon_secret_key
      remoteRef:
        key: matrix/synapse
        property: macaroon_secret_key
    - secretKey: form_secret
      remoteRef:
        key: matrix/synapse
        property: form_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-oidc-credentials
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: matrix-oidc-credentials
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: keycloak/synapse
        property: client_secret
