apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - external-secrets.yaml
  - postgresql-pvc.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - synapse-configmap.yaml
  - synapse-pvc.yaml
  - synapse-deployment.yaml
  - synapse-service.yaml
  - mas-configmap.yaml
  - mas-deployment.yaml
  - mas-service.yaml
  - mas-external-secret.yaml
  - element-configmap.yaml
  - element-deployment.yaml
  - element-service.yaml
  - route.yaml
  - network-policies.yaml
