apiVersion: v1
kind: Service
metadata:
  name: mas
  namespace: matrix
  labels:
    app: mas
spec:
  type: ClusterIP
  selector:
    app: mas
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
