apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mas-credentials
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mas-credentials
    creationPolicy: Owner
  data:
    - secretKey: encryption_secret
      remoteRef:
        key: matrix/mas
        property: encryption_secret
    - secretKey: shared_secret
      remoteRef:
        key: matrix/mas
        property: shared_secret
    - secretKey: db_password
      remoteRef:
        key: matrix/mas
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mas-oidc-credentials
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mas-oidc-credentials
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: keycloak/mas
        property: client_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mas-signing-keys
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mas-signing-keys
    creationPolicy: Owner
  data:
    - secretKey: rsa.pem
      remoteRef:
        key: matrix/mas
        property: rsa_key
    - secretKey: ec.pem
      remoteRef:
        key: matrix/mas
        property: ec_key
