apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-postgresql-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Gi
