apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-media-store
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
