apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-config
  namespace: matrix
data:
  homeserver.yaml: |
    server_name: "matrix.${INTERNAL_DOMAIN}"
    public_baseurl: "https://matrix.${DOMAIN}"
    pid_file: /data/homeserver.pid
    serve_server_wellknown: true
    listeners:
      - port: 8008
        tls: false
        type: http
        x_forwarded: true
        resources:
          - names: [client, federation]
            compress: false
    database:
      name: psycopg2
      args:
        host: matrix-postgresql
        database: synapse
        user: synapse
        password: "${SYNAPSE_DB_PASSWORD}"
        cp_min: 5
        cp_max: 20
    media_store_path: /data/media_store
    enable_registration: false
    enable_registration_without_verification: false
    log_config: "/config/log.config"
    suppress_key_server_warning: true
    trusted_key_servers:
      - server_name: "matrix.org"
    matrix_authentication_service:
      enabled: true
      endpoint: "http://mas:8080"
      secret: "${MAS_SHARED_SECRET}"
    experimental_features:
      msc4108_enabled: true
    registration_shared_secret: "${SYNAPSE_REGISTRATION_SHARED_SECRET}"
    macaroon_secret_key: "${SYNAPSE_MACAROON_SECRET_KEY}"
    form_secret: "${SYNAPSE_FORM_SECRET}"
    caches:
      global_factor: 2.0
    report_stats: false
    signing_key_path: /data/signing.key
  log.config: |
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    loggers:
      synapse.storage.SQL:
        level: WARNING
    root:
      level: INFO
      handlers: [console]
    disable_existing_loggers: false
