---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plane-postgresql
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: plane-postgresql
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: plane
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plane-app-env
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: plane-app-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        DATABASE_URL: "postgresql://plane:{{ .db_password }}@plane-postgresql.plane.svc.cluster.local:5432/plane"
        REDIS_URL: "redis://plane-redis.plane.svc.cluster.local:6379/"
        AMQP_URL: "amqp://plane:{{ .rabbitmq_password }}@plane-rabbitmq.plane.svc.cluster.local:5672/plane"
  data:
    - secretKey: secret_key
      remoteRef:
        key: plane
        property: secret_key
    - secretKey: db_password
      remoteRef:
        key: plane
        property: db_password
    - secretKey: rabbitmq_password
      remoteRef:
        key: plane
        property: rabbitmq_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plane-rabbitmq-creds
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: plane-rabbitmq-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RABBITMQ_DEFAULT_PASS: "{{ .rabbitmq_password }}"
        RABBITMQ_DEFAULT_USER: "plane"
  data:
    - secretKey: rabbitmq_password
      remoteRef:
        key: plane
        property: rabbitmq_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plane-oidc-env
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: plane-oidc-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GITEA_CLIENT_ID: "{{ .oidc_client_id }}"
        GITEA_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        GITEA_HOST: "{{ .oidc_host }}"
  data:
    - secretKey: oidc_client_id
      remoteRef:
        key: plane
        property: oidc_client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: plane
        property: oidc_client_secret
    - secretKey: oidc_host
      remoteRef:
        key: plane
        property: oidc_host
