apiVersion: v1
kind: PersistentVolume
metadata:
  name: plane-pg-iscsi
  labels:
    app: plane-postgresql
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: "${VAULT_SECONDARY_IP}:3260"
    iqn: "iqn.2026-03.farm.haist:okd-plane-pg"
    lun: 0
    fsType: "ext4"
    readOnly: false
