apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plane-postgresql-data
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: plane-pg-iscsi
  resources:
    requests:
      storage: 15Gi
