---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-postgresql-data
  namespace: backstage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Gi
